name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - run: echo "secrets.GITHUB_TOKEN - ${{ secrets.GITHUB_TOKEN }}"
    - name: Label ussyes
      uses: andymckay/labeler@1.0.2
      with: 
        add-labels: "triage"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
